version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5436:5432
    env_file:
      - .env
    networks:
      - petkeepers
  test-db:
    image: postgres:13
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petkeepers-db
    networks:
      - petkeepers
networks:
  petkeepers: